### ISSUE TITLE
Chromoformer regression

### ISSUE THREAD

**Issue by Al-Murphy** [dohlee/chromoformer#4]
Hi!

I'm trying to train chromoformer - regression for the  expression level regression task. Where models were trained to predict log2-transformed RPKM values. Is the [dataloader](https://github.com/dohlee/chromoformer/blob/master/chromoformer/data.py) and [model architecture](https://github.com/dohlee/chromoformer/blob/master/chromoformer/train.py) set up for this anywhere or does it need to be changed? 

I don't see anything returned by the dataloader currently that looks like the log2-transformed RPKM values although it does return label. Should I just swap this out for the `expression` value from the meta dataset or does it also need to be log transformed? Also should I thus change the output head to be suitable for regression?

Cheers,
Alan.

**Comment by Al-Murphy** [comment]
Also, apologies but could you please explain each of the output items by the dataloader? I can't figure out some (or most realistically) so I just want to ensure I know what they are:
```
'label', 'x_p_2000', 'x_pcre_2000', 'pad_mask_p_2000', 'pad_mask_pcre_2000', 'interaction_mask_2000', 'x_p_500', 'x_pcre_500', 'pad_mask_p_500', 'pad_mask_pcre_500', 'interaction_mask_500', 'x_p_100', 'x_pcre_100', 'pad_mask_p_100', 'pad_mask_pcre_100', 'interaction_mask_100', 'interaction_freq'
```
Thanks for your help!

**Comment by Al-Murphy** [comment]
I've figured it out by working through the code, thanks!

**Comment by ytang0831** [comment]
Hi, Murphy！ @Al-Murphy

How did you do to get the predicted RPKM result?  I ran the demo script, and the "prediction" returned seems not to be RPKM vlaues.  
Many thanks!

**Comment by Al-Murphy** [comment]
Yeah you will need to change the `Roadmap3D` class in the `chromoformer/data.py` file to return the `np.log2(meta.expression+1)` rather than the `label`. I do believe the author is working to release a version to do this too though
