### ISSUE TITLE
demo_meta.predicted.csv format details

### ISSUE THREAD

**Issue by ytang0831** [dohlee/chromoformer#6]
HI! 
I noticed that in the output csv, the column are gene_id,expression,eid,label,chrom,start,end,strand,split,neighbors,scores,prediction.

what does "prediction" meaning?   log2expression or prediction accuracy?

Many thanks!

**Comment by ytang0831** [comment]
Also, how can I get the result of predicted RPKM?

**Comment by dohlee** [comment]
Sorry for the late reply. In the previous version of the model (as in your case), the `prediction` column represents the probability of a gene expression being greater than the median (1) or not (0).

At this moment we are undergoing a major update to the repository for the usability of the model, and you can get predicted RPKM by training `ChromoformerRegressor` model.

Please let me know if there are any difficulties using our model. Thanks!

**Comment by ytang0831** [comment]
@dohlee, Thanks for your update, but I found a problem.

When I want to implement chromoformer regression prediction on the test set, I used run_demo.py because there is only the trian.py script but no test script. But run_demo.py is  a script for binary predictions. predictions.append(torch.sigmoid(out.cpu()).numpy()[:, 1]) should be changed to predictions.append(out.cpu().numpy())?

**Comment by dohlee** [comment]
Please refer to `run_demo_regression.py`. It might solve the problem.

Closing this issue. Please open a new one if you have any further issue!
